- tox.ini
> Add python3.8 & python3.9 to envlist in tox.ini

- integration_tests/test_dbapi.py
- trino/client.py
Currently, `cursor.description` only loaded when data is fetched.
That make Trino's sqlalchemy dialect don't work. See [sqlalchemy's ResultProxy](https://github.com/sqlalchemy/sqlalchemy/blob/rel_1_3_23/lib/sqlalchemy/engine/result.py#L793-L811)
Signed-off-by: Đặng Minh Dũng <dungdm93@live.com>
> eager-loading cursor.description

- trino/client.py
If Trino returns the query result in the first HTTP call, the `columns` property is not set so the library throws the` Cursor must be loaded before call TrinoResultMetaData` exception.
> Fix bug when the query result is returned in first HTTP call

- .github/workflows/ci.yml
> Add pypy3 for ci

- tests/integration/test_dbapi_integration.py
- trino/client.py
- trino/dbapi.py
> Expose info_uri from query status in Cursor

- README.md
> Fix README Cursor.fetchone method

- setup.py
Signed-off-by: Đặng Minh Dũng <dungdm93@live.com>
Fixed #135
> fix: package don't include module `trino.sqlalchemy`

- tests/unit/sqlalchemy/test_compiler.py
- trino/sqlalchemy/compiler.py
The origin PR is https://github.com/dungdm93/sqlalchemy-trino/pull/37
> Overwrite `limit_clause` in `TrinoSQLCompiler`

- trino/sqlalchemy/dialect.py
This is the same approach as pymssql. This commit adds SQLAlchemy support for version < 352. The another way to get server version is getting from `system.runtime.nodes` table, but the environment may disallow accessing the catalogs.
> Return None when failed to get server version in SQLAlchemy

- tests/integration/test_dbapi_integration.py
- trino/client.py
- trino/dbapi.py
> Add support for executemany in DBAPI

- tests/integration/test_dbapi_integration.py
- trino/client.py
- trino/dbapi.py
Fixes #54 
The issue also mentions support for map data type, which is implemented in a separate commit.
> Support Infinity and nan in experimental_python_types

- tests/integration/test_dbapi_integration.py
- tests/unit/test_client.py
- tests/unit/test_dbapi.py
- trino/client.py
- trino/constants.py
- trino/dbapi.py
Fixes #154 
Co-authored-by: abrisan <s1505883@sms.ed.ac.uk>
> Add support for client tags in Python API

- tests/integration/test_dbapi_integration.py
- trino/client.py
- trino/dbapi.py
> Support Trino's `ROW` datatype

- tests/unit/test_client.py
- trino/client.py
- trino/exceptions.py
Fixes: https://github.com/trinodb/trino-python-client/issues/182
> Retry on 502 bad gateway responses

- README.md
- tests/integration/test_dbapi_integration.py
- tests/unit/sqlalchemy/test_dialect.py
- trino/client.py
- trino/dbapi.py
- trino/sqlalchemy/dialect.py
- trino/transaction.py
> Configure `experimental_python_types` through `dbapi.Connection`

- tests/integration/conftest.py
- tests/integration/test_dbapi_integration.py
- tests/unit/test_client.py
- tests/unit/test_dbapi.py
- trino/client.py
- trino/constants.py
- trino/dbapi.py
> Support `USE catalog.schema` statements

- README.md
Resolves https://github.com/trinodb/trino-python-client/issues/52
> Document how to use verify parameter

- tests/integration/test_dbapi_integration.py
- tests/unit/test_client.py
- trino/client.py
- trino/constants.py
Add support for SET ROLE statement
Fixes https://github.com/trinodb/trino-python-client/issues/7
Follow-up of closed PR https://github.com/trinodb/trino-python-client/pull/196.
> Add support for SET ROLE statement

- tests/integration/test_sqlalchemy_integration.py
- trino/sqlalchemy/dialect.py
> Integration tests for common sqlalchemy operations

- trino/client.py
> Log http response in TrinoQuery#cancel at debug instead of info

- trino/sqlalchemy/dialect.py
> specify `catalog_name` in `get_table_comment`

- CHANGES.md
Assemble the release notes for the upcoming Trino Python Client 0.317.0 release.
N/A
(x) This is not user-visible and no release notes are required.
Format: committer/maintainer, PR/issue number, ✅ / ❌ rn ✅
✅ rn - release note added and verified, or assessed to be not necessary, set to ❌ rn before completion
@ebyhr #247 ✅
@hashhar #254 ✅
@hashhar #249 ✅
@hashhar #255 ✅
@hashhar #258 ✅
> Add 0.318.0 release notes

- .github/workflows/ci.yml
CI maintenance - replace deprecated GH actions. 
```markdown
```
> Bump GH actions version

- .github/workflows/release.yml
- .pre-commit-config.yaml
- README.md
- setup.cfg
- trino/auth.py
Enable mypy checks for auth.py and other small enhancements like add some generic hooks in pre-commit, bump pre-commit hooks version and adjust release section in DEVELOPMENT.md.
I'll work on enabling mypy checks for other modules as a follow-up.
```markdown
```
> Enable mypy checks for auth.py and other small enhancements

- tests/integration/test_types_integration.py
- trino/client.py
- simplified the code to only apply rounding if the input value exceeds Python's supported precision.
- Removed usage of regexes for performance
- Usage of fromisoformat instead of strptotime to get a 54x boost in performance
- Rounding using Decimal supporting overflow
> Simplify temporal value mappers

- tests/integration/test_dbapi_integration.py
- trino/dbapi.py
Expose `query_id` property on `dbapi.Cursor`
```markdown
* Expose `query_id` property on `dbapi.Cursor`
```
> Expose `query_id` property on `dbapi.Cursor`

- trino/dbapi.py
> Close http session on connection.close()

- CHANGES.md
Assemble the release notes for the upcoming 0.320.0 release. Fixes https://github.com/trinodb/trino-python-client/issues/283
N/A
Format: committer/maintainer, PR/issue number, ✅ / ❌ ✅ - release note added and verified, or assessed to be not necessary, set to ❌ before completion
@hashhar #269 ✅
@hashhar #284 ✅
@hashhar #295 ✅
```markdown
```
> Release notes for 0.320.0

- setup.py
- tests/integration/test_sqlalchemy_integration.py
Rewrite tests to not depend on non-SQLAlchemy code
> Rewrite tests to not depend on non-SQLAlchemy code

- tests/unit/test_client.py
- trino/client.py
> Add deprecation warning for ROLE{} pattern

- .github/DEVELOPMENT.md
- setup.py
- tests/integration/conftest.py
This PR will use the already locally running Trino server instead of starting a new instance for every module. This saves us some time running tests and is easier for debugging as the server is not stopped after running the tests and doesn't use a random port.
It also removes some (broken) legacy code for running tests and managing docker.
```markdown
```
> Use local server if available

- .pre-commit-config.yaml
> Update versions of pre-commit, isort and mypy types

- CHANGES.md
Assemble the release notes for the upcoming 0.321.0 release. Fixes #321.
N/A
Format: committer/maintainer, PR/issue number, ✅ / ❌ ✅ - release note added and verified, or assessed to be not necessary, set to ❌ before completion
@hashhar #325 ✅
@hashhar #328 ✅
@hashhar #323 ✅
@hashhar #340 ✅
> Release notes for 0.322.0

- tests/integration/test_dbapi_integration.py
- trino/dbapi.py
Fixes #347 
```markdown
* Fix Decimal with scientific notation conversion
```
> Fix Decimal with scientific notation conversion

- tests/integration/test_dbapi_integration.py
- trino/dbapi.py
Support TIME WITH TIME ZONE in prepared statements
```markdown
```
> Support TIME WITH TIME ZONE in prepared statements

- CHANGES.md
Release notes for 0.324.0. Fixes #370.
> Release notes for 0.324.0

- setup.py
Bump min requests version to 2.31.0
```markdown
```
> Bump min requests version to 2.31.0

- CHANGES.md
> Release notes for 0.325.0

- tests/integration/test_dbapi_integration.py
- tests/unit/sqlalchemy/test_dialect.py
- trino/dbapi.py
- trino/sqlalchemy/dialect.py
> Fix handling of legacy_prepared_statements parameter

- CHANGES.md
Fixes https://github.com/trinodb/trino-python-client/issues/379
> Release notes for 0.326.0

- .github/workflows/ci.yml
- README.md
> Update SQLAlchemy compatibility section

- README.md
- setup.py
The `README.md` contains the full long description such as documentation. The current text is not comprehensive as `README.md`. This file is ignored during installation and the content is lost when it's published.
For example https://pypi.org/project/trino/ shows 
After this change it will be like the `requests` package https://pypi.org/project/requests/ which [defines](https://github.com/psf/requests/blob/ee93fac6b2f715151f1aa9a1a06ddba9f7dcc59a/setup.py#L88) a long markdown description.
The readme content will be published in the package.
```markdown
* Fix some things. …
```
> add markdown long description

- CHANGES.md
Fixes https://github.com/trinodb/trino-python-client/issues/382
> Release notes for 0.327.0

- .github/workflows/ci.yml
- README.md
- setup.py
See https://devguide.python.org/versions/ and https://www.pypy.org/ for currently supported versions.
> Update tested Python and PyPy versions

- tests/integration/conftest.py
- trino/client.py
- trino/dbapi.py
These can contain sensitive data and weren't useful outside of debugging locally.
> Remove sensitive debug logs

- README.md
- setup.py
> Some cleanups

- CHANGES.md
Fixes https://github.com/trinodb/trino-python-client/issues/452
> Release notes for 0.329.0

- CHANGES.md
> Release notes for 0.331.0

- CHANGES.md
> Release notes for 0.332.0

- CHANGES.md
Fixes https://github.com/trinodb/trino-python-client/issues/516
> Add 0.333.0 release notes

- CHANGES.md
> Amend 0.333.0 release notes

- CHANGES.md
Fixes https://github.com/trinodb/trino-python-client/issues/566
> Release notes for 0.335.0

- setup.py
Bump requests to 2.32.4 to address CVE-2024-47081
```markdown
```
> Bump requests to 2.32.4 to address CVE-2024-47081
