- .travis.yml
Based on @ggreg 's comment https://github.com/prestosql/python-client/pull/2#issuecomment-573450675.
> Remove support for pypy-5.4 in Travis CI

- presto/client.py
- presto/dbapi.py
- tests/test_client.py
Let the HTTP session handler the redirects with `allow_redirects=True`
by default.
Fixes https://github.com/prestosql/presto-python-client/issues/17
> Remove default redirect_handler

- presto/client.py
- presto/dbapi.py
This PR exposes the verify parameter to explicitly specify client certificate path.
This resolves #29
> Expose verify parameter on dbapi.connect

- integration_tests/test_dbapi.py
- presto/dbapi.py
> Make Cursor implement iterable

- integration_tests/test_dbapi.py
- presto/dbapi.py
Fixes a runtime error with added_prepare_header variable not being
present when an exception happens during creation of a prepared
statement.
> Fix referenced before assignment error in execute

- integration_tests/test_dbapi.py
- presto/dbapi.py
Prior to this commit parameters passed to execute were added to the
EXECUTE statement as naked strings. When using strings this causes a
syntax error in the query because Presto thinks it's a constant.
Example:
```
EXECUTE "st-XXX" USING Bob
```
results in:
```
Query 20201014_232548_02077_8sytd failed: line 1:22: Constant expression cannot contain column references
```
In this commit, string parameters passed to the execute are single
quoted to form a proper query. Care has been taken to escape single
quotes to avoid other query syntax errors and SQL injection.
> Fix use of string parameters in prepared statements

- integration_tests/fixtures.py
- integration_tests/test_dbapi.py
- presto/dbapi.py
- setup.py
Prior to this commit, the only python types supported as query parameters were str and int. In this commit the types are expanded to bool, float, bytes, datetime, list, dict, and UUID.
>  Handle python types for query parameters

- presto/client.py
- presto/exceptions.py
When comparing `presto-python-client` with `pyhive` for performance reasons, I found this client to run extremely slow for queries with large throughput. Running `line_profiler` on `fetchall()`, we see this:
```
Total time: 42.8376 s
dbapi.py
Function: fetchall at line 470
Line #      Hits         Time  Per Hit   % Time  Line Contents
==============================================================
470                                               def fetchall(self):
471                                                   # type: () -> List[List[Any]]
472         1   42837588.0 42837588.0    100.0          return list(self.genall())
Total time: 14.4723 s
client.py
Function: process at line 397
Line #      Hits         Time  Per Hit   % Time  Line Contents …
```
> Change logging formatting to lazily evaluate (performance critical)

- README.md
- integration_tests/fixtures.py
- integration_tests/test_dbapi.py
- tests/test_client.py
- tests/test_exceptions.py
- trino/auth.py
- trino/client.py
- trino/constants.py
- trino/dbapi.py
- trino/exceptions.py
- trino/transaction.py
replaced almost every occurrence of "presto" with "trino".
README.md migrated, too -- except the Presto book link
changed default version of Trino for integration tests to 351
> Complete transition to Trino

- .github/workflows/ci.yml
- integration_tests/conftest.py
- integration_tests/test_dbapi.py
- setup.cfg
- setup.py
- tests/test_client.py
- trino/__init__.py
- trino/dbapi.py
Added flake8 to the GitHub CI tests and then updated the code to pass flake8 test. Some unused imports were removed.
The max line length is set to 120 and the W503 rule is ignored which is PEP 8 compliant.
> Added flake8 test and updated affected code

- README.md
- trino/auth.py
The recent version of trino has the JWT authentication method so this PR adds support for JWT authentication in `trino-python-client`. I have updated documentation in `README` as well for the usage of JWT authentication.  Please let me know if any improvement is needed.
> Add support for JWT Authentication 

- .github/workflows/ci.yml
- README.md
- integration_tests/conftest.py
- integration_tests/test_dbapi.py
- setup.py
- tests/test_client.py
- tests/test_exceptions.py
- tox.ini
- trino/__init__.py
- trino/auth.py
- trino/client.py
- trino/constants.py
- trino/dbapi.py
- trino/exceptions.py
- trino/logging.py
- trino/transaction.py
> Drop python2 support

- .github/workflows/ci.yml
- README.md
- setup.py
- trino/auth.py
- trino/client.py
- trino/constants.py
- trino/dbapi.py
This PR includes the following updates:
1. Dropping Python 3.5 support
2. Removing Python 2 type annotations
> Drop Python 3.5 support

- trino/client.py
Moved the setter for the cancelled property following the check that the cancellation is successful.
> Set query cancelled property only after cancelling

- setup.py
Click is only needed for integration tests and not for actual usage.
Add click to tests extra instead.
> Remove click from install requirements

- .github/workflows/ci.yml
- .pre-commit-config.yaml
- setup.py
- trino/client.py
Relates to #69. Also see [`pre-commit`](https://pre-commit.com/).
> Add pre-commit as a Flake8 and MyPy delegate

- tests/test_client.py
Used simple SELECT query to generate the stacktrace.
```
trino> select * from orders;
Query 20210817_140827_00000_arvdv failed: line 1:15: Schema must be specified when session schema is not set
io.trino.spi.TrinoException: line 1:15: Schema must be specified when session schema is not set
at io.trino.sql.analyzer.SemanticExceptions.semanticException(SemanticExceptions.java:48)
at io.trino.sql.analyzer.SemanticExceptions.semanticException(SemanticExceptions.java:43)
at io.trino.metadata.MetadataUtil.lambda$createQualifiedObjectName$3(MetadataUtil.java:152)
...
```
> Use Trino JSON response as test example

- README.md
- tests/unit/test_client.py
- trino/auth.py
- trino/client.py
- trino/exceptions.py
Support full flow for the OAuth2 based trino server. This is similar to the trino-cli.
The application using the trino library can override to load the authentication user via browser, by default it will print it on stdout.
> Support full Oauth2 flow for authentication

- README.md
The current documentation for BasicAuthentication does not make it explicit which authentication method can be used for a python client. This fixes the documentation and gives reference to original documentation as well. 
Ref: https://trinodb.slack.com/archives/CFPVDCDHV/p1636611957009300
> Update Readme docs for Authentication methods

- setup.py
- tests/unit/test_client.py
- trino/auth.py
- trino/client.py
The benefits of this approach are:
* there's no need for retrying 401 (Unauthorized) as the same connection
is being reused,
* the whole authentication uses the same context (PROXIES, SSL verify
etc.) so no need for client's setup duplication.
Additionally, OAuth2 client's tests were rewritten using HTTPretty which
stubs/mocks the http layer and makes changing implementation details
easier.
> Reuse the same connection when getting a token

- README.md
The main addition is `pip install .[tests]` which is equivalent to the more manual `pip install -r requirements.txt`.
> Document developer setup in README.md

- trino/__init__.py
This reverts commit f9e68da9bcf532f50aff544a13ebb54af365b329.
This change broke the README code snippets with an error like "Cannot find reference 'dbapi' in '__init__.py'.
> Fix broken module import

- tests/integration/test_dbapi_integration.py
This reverts commit 3ce46fe317da1e01ad7d41970415bdab5db025fe.
The user-facing API (and documentation) is to import the trino package
instead of the specific trino.dbapi module. Integration tests should
test using the import that is documented and part of API.
> Revert "Use more specific module imports in tests"

- README.md
- tests/unit/test_client.py
- trino/client.py
- trino/constants.py
- trino/dbapi.py
Fixes #6
<strike>One thing I'm not sure is the key-value pair should be `key=value` (https://github.com/trinodb/trino-python-client/issues/6#issuecomment-586734438) or `key:value` (see the [JDBC parameter reference](https://trino.io/docs/current/installation/jdbc.html?highlight=extra%20credential#parameter-reference))</strike>
quote https://github.com/trinodb/trino-python-client/pull/116#discussion_r730947560
1. extra credentials pair `k=v` are joined by `=` while pairs are chained into a single header value by separater `, ` (comma and space).
2. extra credential key must not be empty, it contains ASCII charaters only, whitespace and `=` (equal sign) are disallowed.
3. extra credential value could be empty, and is encoded into [application/x-www-form-urlencoded MIME …
> Add new parameter 'extra_credential'

- .github/workflows/ci.yml
- tests/integration/conftest.py
- tests/integration/test_dbapi_integration.py
Currently we only test the client against first Trino version i.e. 351.
This means that any changes in future versions that cause the client to break aren't caught by CI.
See https://github.com/trinodb/trino-go-client/pull/28 for motivation.
> Add latest Trino version to test matrix

- README.md
- trino/auth.py
Add `CertificateAuthentication` class to support cert based authentication.
Re: https://github.com/trinodb/trino-python-client/issues/30
> Add `CertificateAuthentication` class to support cert based authentication

- .github/workflows/ci.yml
- README.md
- setup.py
- tox.ini
Existing matrix became 14 jobs long.
We don't need to test older Trino versions with every single Python version - just the latest is enough. Matrix is now 7 jobs long.
> Trim CI matrix and prepare for explicit backward compatibility tests

- tests/integration/conftest.py
- tests/integration/test_dbapi_integration.py
- trino/dbapi.py
When an explicit transaction was started in auto-commit mode, the transaction request was not correctly attached to the cursor. That caused query and transaction were executed separately. Query was executed in separate transaction and request. 
Issue #129 
Design consideration
Starting a separate transaction in auto-commit may be disabled at all. It wasn't working, until now. If user wants to manage transaction separately can use connection in other isolation level than auto-commit.
> Fix transaction handling in auto-commit mode

- README.md
- setup.py
- tests/integration/test_dbapi_integration.py
- trino/client.py
- trino/dbapi.py
- trino/exceptions.py
> Support decimal, date, time, timestamp with time zone and timestamp python types in prepared statements and result sets

- setup.py
It's possible for users to switch between experimental Python types and
the old types on the fly and is not something they will decide when
installing the module. So the module must include pytz as a required
dependency.
Fixes https://github.com/trinodb/trino-python-client/issues/165
> Install pytz by default as a dependency

- README.md
- setup.py
- tests/unit/oauth_test_utils.py
- tests/unit/test_client.py
- tests/unit/test_dbapi.py
- trino/auth.py
> Support redirection through webbrowser for OAuth authentication

- README.md
- tests/unit/sqlalchemy/test_dialect.py
- trino/sqlalchemy/dialect.py
Resolves https://github.com/trinodb/trino-python-client/issues/106 and https://github.com/trinodb/trino-python-client/issues/108
> SqlAlchemy tweaks

- tests/unit/sqlalchemy/conftest.py
- tests/unit/sqlalchemy/test_datatype_parse.py
- trino/sqlalchemy/compiler.py
- trino/sqlalchemy/datatype.py
First point from https://github.com/trinodb/trino-python-client/issues/107
> Support for TIME(p) and TIMESTAMP(p) to SQLAlchemy

- tests/unit/sqlalchemy/test_compiler.py
- trino/sqlalchemy/dialect.py
This is a quick fix to add a flag to the SQLAlchemy Dialect class that supports proper `INSERT` statement compilation when using CTEs. The Trino SQL dialect expects the CTE declarations to come after the `INSERT` keyword in a `INSERT INTO ...  SELECT` statement. Fortunately, SQLAlchemy already has a flag to handle this properly, so just setting it to `True` here in the Dialect class.
> Add cte_follows_insert flag to SQLAlchemy Dialect to support proper statement creation

- tests/integration/test_dbapi_integration.py
- trino/dbapi.py
> Cancel current query on `cursor.close()`

- trino/sqlalchemy/dialect.py
Currently, in un-partitioned table, trino driver still return a single-value list of a partition index with **empty columns**
So, it's better to **return empty list** instead.
> return empty list in un-partitioned table

- tests/unit/sqlalchemy/test_compiler.py
- trino/sqlalchemy/compiler.py
This change allows for specifying a `trino_catalog` table argument to SQLALchemy Table objects, which is then checked when compiling statements and prepended to the proper objects. This allows for writing queries that talk to multiple catalogs at the same time.
This change was largely implemented by @AlexandreOuellet in the [PyHive](https://github.com/dropbox/PyHive) repository, with some minor edits by @VinceDPM and myself. However, since that repository is no longer well-maintained, and since Trino seems to have better support currently than Presto on the whole, I have switched my own focus to using Trino, and thus wanted to get this functionality working here as well.
As this is the first time I've attempted to contribute here, please let me know if I am missing anything in this PR! It …
> Add ability to specify catalog as a SQLALchemy table argument

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
Following PR improves the Create issue form in github.
the last button refers to the #python-client Trino slack channel.
> Add GitHub issue forms

- tests/integration/test_types_integration.py
- trino/client.py
Optimizes the `experimental_python_types` flag. Instead of checking the type for each row, check the type once for each `fetch()` call and compute a list of lambdas which are to be applied to the values from each row.
- A new `RowMapperFactory` class was created to wrap this behavior. The `columns` content from the status is analyzed and a list of lambda functions is created (one lambda per column)
- The `experimental_python_types` flag is now processed in the `TrinoQuery` class instead of the `TrinoResult` class
> Optimize the experimental python types flag

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
Issues must be triaged before being labelled as a bug - which confirms
it's a bug to be fixed instead of just using something wrong or being
labelled as an enhancement - which confirms it's something we think
should be added.
> Don't automatically label issues

- .github/workflows/ci.yml
- tests/integration/test_dbapi_integration.py
- tests/unit/conftest.py
- tests/unit/test_client.py
- tests/unit/test_dbapi.py
- trino/client.py
- trino/dbapi.py
- trino/sqlalchemy/dialect.py
Fixes #232, #95
Ensures the received data is properly acknowledged by calling the next_uri. This will avoid seeing failed queries in the query log when executing scalar queries as in the following example.
```
cur.execute("SELECT VERSION()")
cur.fetchone()
cur.cancel()
```
( ) This is not user-visible and no release notes are required.
```markdown
* Make the `execute` method of the cursor block until at-least one row is received.
This means users no longer need to call `fetchone` or `fetchall` to make sure query
actually starts executing on the Trino server. Note that results still need to be consumed
by calling `fetchone` or `fetchall` to make sure …
```
> Acknowledge reception of data in `TrinoResult`

- README.md
wheel may not be preinstalled within a virtual environment and will cause `./setup.py sdist bdist_wheel` to fail with `error: invalid command 'bdist_wheel'`
(x) This is not user-visible and no release notes are required.
> Improve release process documentation

- tests/integration/test_sqlalchemy_integration.py
- trino/sqlalchemy/compiler.py
- trino/sqlalchemy/datatype.py
Implement the ability to reference JSON columns using SQLAlchemy. This allows JSON columns to be created in new tables, as well as writes to/reads from them using normal Python `json` module serialization/deserialization.
Originally referenced [in this issue](https://github.com/trinodb/trino-python-client/issues/194).
( ) This is not user-visible and no release notes are required.
```markdown
* Add support for creating tables containing `JSON` columns and reading and writing to them with SQLAlchemy. ([#194](https://trinodb/trino-python-client/issues/194))
```
> Add JSON functionality to SQLAlchemy Dialect

- tests/unit/sqlalchemy/test_compiler.py
- trino/sqlalchemy/compiler.py
Fixes #237 
( ) This is not user-visible and no release notes are required.
Resolved `'TableClause' object has no attribute 'dialect_options'` exception by checking for `DialectKWArgs` implementation.
> Fix 'TableClause' object has no attribute 'dialect_options'

- tests/integration/test_dbapi_integration.py
- tests/unit/test_client.py
- trino/client.py
- trino/dbapi.py
- trino/exceptions.py
The prepared statement handling code assumed that for each query we'll
always receive some non-empty response even after the initial response
which is not a valid assumption.
This assumption worked because earlier Trino used to send empty fake
results even for queries which don't return results (like PREPARE and
DEALLOCATE) but is now invalid with
https://github.com/trinodb/trino/commit/bc794cd49a616fa95eecfcc384b761f67176240b.
The other problem with the code was that it leaked HTTP protocol details
into dbapi.py and worked around it by keeping a deep copy of the request
object from the PREPARE execution and re-using it for the actual query
execution.
The new code fixes both issues by processing the prepared statement
headers as they are received and storing the resulting set of active …
> Fix prepared statement handling

- .github/CONTRIBUTING.md
- .github/DEVELOPMENT.md
- .github/pull_request_template.md
- .github/workflows/ci.yml
- README.md
Adding DEVELOPMENT.md and CONTRIBUTING.md
Clarify process of contributing to the project.
> Improve contribution process

- README.md
- tests/integration/test_dbapi_integration.py
- tests/unit/sqlalchemy/test_dialect.py
- tests/unit/test_client.py
- tests/unit/test_dbapi.py
- trino/client.py
- trino/dbapi.py
- trino/sqlalchemy/dialect.py
> Support setting roles in dbapi and sqlalchemy

- README.md
- tests/unit/sqlalchemy/test_dialect.py
- trino/sqlalchemy/__init__.py
- trino/sqlalchemy/dialect.py
- trino/sqlalchemy/util.py
Currently it is not possible to create a Trino url  in sqlalchemy urls containing characters like &, ' ' or @. The values should be properly encoded and decoded.
This PR provides a helper method that properly encodes the passed values and ensures that values are properly decoded before passing down as `dbapi.connect` parameters.
```
>>> URL(
...                         user="user@test.org/my_role",
...                         password="pass /*&",
...                         host="localhost",
...                         session_properties={"query_max_run_time": "1d"},
...                         http_headers={"trino": 1},
...                         extra_credential=[
...                             ("user1@test.org/my_role", "user2@test.org/my_role"),
... …
```
> Escape url parameters in sqlalchemy connection strings

- CHANGES.md
Assemble the release notes for the upcoming Trino Python Client 0.317.0 release.
N/A
(x) This is not user-visible and no release notes are required.
Format: committer/maintainer, PR/issue number, ✅ / ❌ rn ✅
✅ rn - release note added and verified, or assessed to be not necessary, set to ❌ rn before completion
@hashhar #220 ✅ rn
@hashhar #221 ✅ rn
@hashhar #236 ✅ rn
@hashhar #214 ✅ rn
@ebyhr #240 ✅ rn
@hashhar #242 ✅ rn
@hashhar #239 ✅ rn
@hashhar #212 ✅ rn
@hashhar #235 ✅ rn
> Add 0.317.0 release notes

- trino/client.py
If multiple connections are created from same passed parameters (eg session properties, client tags, roles, ...), changes in one connection's client_session should not affect other connections.
```markdown
```
> Make defensive copy of reference types in `ClientSession`

- trino/client.py
Resolves #248 
`X-Trino-Deallocated-Prepare` may appear on multiple responses. Query execution should not fail on prepared statement removal if the prepared statement has already been removed.
```markdown
* Fix failure on already removed deallocated prepared statement headers
```
> Ignore already removed deallocated prepared statement headers

- tests/integration/test_sqlalchemy_integration.py
- trino/sqlalchemy/dialect.py
Fixes #253 
```markdown
* Fix 'Engine' object has no attribute 'connection', when calling `get_table_comment` from Superset with sqlalchemy 1.3 
```
> Fix 'Engine' object has no attribute 'connection'

- README.md
- tests/integration/test_dbapi_integration.py
Some random cleanups.
Some random cleanups.
> Random cleanups

- trino/sqlalchemy/util.py
Fix a compatibility issue with SQLAlchemy v1.4.42, resolves https://github.com/trinodb/trino-python-client/issues/273
```markdown
* Fix a compatibility issue with _rfc_1738_quote in SQLAlchemy v1.4.42 (issue 273)
```
> Fix a compatibility issue with SQLAlchemy v1.4.42

- trino/exceptions.py
Fix typo in TrinoQueryError custom exception class.
Fix simple typo in `TrinoQueryError`
When the error `TrinoQueryError` the user would see a typo in the error text.
(x) Release notes are required, with the following suggested text: 
```markdown
* Fix typo in `TrinoQueryError` error message (Fix exceptions.py typo`276`)
```
> Fix exceptions.py typo

- tests/integration/test_sqlalchemy_integration.py
This is where type enforcement would be really helpful (see https://github.com/trinodb/trino-python-client/pull/208). For the SQLAlchemy dialect the `has_schema` method was being passed the SQLAlchemy engine as opposed to the corresponding connection per [here](https://github.com/trinodb/trino-python-client/blob/master/trino/sqlalchemy/dialect.py#L304-L313). Both objects have an `execute(...)` method which is why the tests worked, however I thought it was prudent to make make sure the callers used the correct arguments. 
```markdown
```
> [tests] Fix TrinoDialect.has_schema arguments

- setup.py
- tests/integration/test_sqlalchemy_integration.py
- trino/sqlalchemy/dialect.py
Per the [SQLAlchemy documentation](https://docs.sqlalchemy.org/en/14/core/reflection.html#sqlalchemy.engine.reflection.Inspector.get_table_names) the `get_table_names` method is intended to return the real table names, i.e., without views. The PR updates the `get_table_names` to only return real table names whereas previously it returned real tables and views.
Note there were no prior integration tests for the `TrinoDialect.get_view_names` method so I added some to cover this logic and threw in a few extra for free which should cover all the various scenarios.
> The …
> [sqlalchemy] Ensure TrinoDialect.get_table_names only returns real tables

- .github/DEVELOPMENT.md
- .github/workflows/ci.yml
- .pre-commit-config.yaml
- setup.py
- tests/integration/conftest.py
- tests/integration/test_dbapi_integration.py
- tests/integration/test_sqlalchemy_integration.py
- tests/integration/test_types_integration.py
- tests/unit/conftest.py
- tests/unit/sqlalchemy/conftest.py
- tests/unit/sqlalchemy/test_compiler.py
- tests/unit/sqlalchemy/test_datatype_parse.py
- tests/unit/sqlalchemy/test_dialect.py
- tests/unit/test_client.py
- tests/unit/test_dbapi.py
- tests/unit/test_http.py
- tests/unit/test_transaction.py
- trino/__init__.py
- trino/auth.py
- trino/constants.py
- trino/dbapi.py
- trino/sqlalchemy/__init__.py
- trino/sqlalchemy/compiler.py
- trino/sqlalchemy/datatype.py
- trino/sqlalchemy/dialect.py
- trino/sqlalchemy/util.py
- trino/transaction.py
Introduces isort (sorting imports)
- Added isort as "test" dependencies
- Run `pre-commit run --all-files` to standardize formatting and import sorting.
> Add isort (for sorting imports)

- tests/unit/test_http.py
- trino/client.py
Addresses #262 .
Handles cases where these config headers are present in the request, but with an empty string as their value. Currently, an error is raised when trying to parse the empty strings. This PR addresses this by checking that these headers are not only present, but not empty.
These headers being present with empty values is not normally expected, although we'd like to protect against it for cases like a proxy sitting in between Trino and the client that is altering the headers (which is the case for me).
Notes: 
- Added checks for all headers in `process` that might hit this issue because the values are parsed. HEADER_SET_SESSION, HEADER_SET_ROLE and HEADER_ADDED_PREPARE are currently failing to parse if the header value is empty
- The test reproduces the error, but I don't …
> Checking for config headers to be both present and non-empty

- tests/integration/test_sqlalchemy_integration.py
- trino/sqlalchemy/dialect.py
Querying the `information_schema.views` table seems to be sub-performant for determining which entities are views—I speculate this is because all the view definitions need to be extracted/compiled. A more performant approach is to use `information_schema.tables` with the appropriate type filter. 
For example for a very large schema at Airbnb (comprising of over 100k entities) the following query,
```sql
SELECT
table_name
FROM 
information_schema.tables
WHERE 
table_schema = '<schema>' AND 
table_type = 'VIEW'
```
took ~ 5 seconds, whereas:
```sql
SELECT
table_name
FROM
information_schema.views
WHERE    
table_schema = '<schema>'
```
was still running after 10 minutes.
Note there were no prior integration tests for the `TrinoDialect.get_view_names` method so I added some to cover this …
> [sqlalchemy] Improve the performance of TrinoDialect.get_view_names

- CHANGES.md
Assemble the release notes for the upcoming 0.319.0 release. Fixes #260
N/A
Format: commit, committer/maintainer, PR/issue number, ✅ / ❌ ✅ - release note added and verified, or assessed to be not necessary, set to ❌ before completion
@ebyhr #274  ✅
@ebyhr #276  ✅
@ebyhr #268 ✅
@ebyhr #266  ✅
@hashhar #263 ✅
@ebyhr #267 ✅
> Add 0.319.0 release notes

- tests/integration/test_types_integration.py
- trino/client.py
Fixes #269
Also refactors mappers from lambda functions to separate classes for better readability.
```markdown
```
> Support `None` values in array, map and row types

- tests/unit/oauth_test_utils.py
- tests/unit/test_client.py
- trino/auth.py
Fixes refresh token issue caused by `Error: header info didn't have x_redirect_server`. Trino coordinator with enabled refresh token after access token expiration will respond with only `x_token_server` field in authentication header, if refresh token has expired then coordinator restarts the flow. 
Fix refresh flow in case Trino cluster has refresh tokens enabled. 
(x) Release notes are required, please propose a release note for me.
```markdown
```
> Fix refresh tokens flow

- .pre-commit-config.yaml
- setup.cfg
- trino/client.py
- trino/exceptions.py
- trino/logging.py
- trino/transaction.py
Even though Mypy is enabled, per [this](https://github.com/trinodb/trino-python-client/blob/master/.pre-commit-config.yaml#L8-L15) pre-commit hook, the default options are fairly loose which allows for untyped methods and calls.
This PR aims to slowly start tightening the screws module by module (resulting in digestible PRs) —starting with `trino.exceptions`, `trino.logging`, and `trino.transactions`—by enforcing typed methods, calls, etc. which improves code clarity and correctness.
The hope is over time contributors can systematically go through module by module and ensure all methods are correctly typed and remove them from the ignore list.
> [mypy] Enforce Mypy checks for a subset of modules

- README.md
- setup.py
- tests/integration/test_dbapi_integration.py
- tests/unit/test_client.py
- trino/client.py
- trino/constants.py
- trino/dbapi.py
Add support for TIMEZONE
Fixes https://github.com/trinodb/trino-python-client/issues/27
> Add support for TIMEZONE

- tests/integration/test_dbapi_integration.py
- tests/integration/test_types_integration.py
- trino/client.py
- trino/dbapi.py
> Support `VARBINARY` query parameter

- tests/integration/test_dbapi_integration.py
- trino/dbapi.py
> Add `Cursor.describe` to retrieve the schema of a query

- tests/integration/test_dbapi_integration.py
- tests/integration/test_types_integration.py
- tests/unit/test_client.py
- trino/client.py
- trino/constants.py
Set X-Trino-Client-Capabilities to PARAMETRIC_DATETIME. Update the unit and integration tests accordingly.
When querying Trino, set the X-Trino-Client-Capabilities HTTP header to PARAMETRIC_DATETIME. This instructs Trino to return full-precision datetimes and times.
(X) Release notes are required, with the following suggested text:
```markdown
* The client is now requesting PARAMETRIC_DATETIME, leading Trino to return full-precision datetimes and times. 
```
> Support variable precision time timestamp

- tests/unit/test_client.py
- trino/client.py
In the jdbc driver custom roles are enclosed in `ROLE{rolename}` automatically. This was not yet implemented in the Trino python client, causing confusion.
This PR adds this enclosing automatically, while checking if the enclosing is not already provided to ensure backwards compatiblity.
```markdown
* Enclose custom roles passed in Connection into Trino protocol specific formatting (ROLE{rolename})
```
> Encode roles as in JDBC driver

- .github/workflows/ci.yml
- setup.py
- tests/integration/test_sqlalchemy_integration.py
- trino/sqlalchemy/dialect.py
In the do_execute function of SQLAlchemy dialect, an if statement was accessing context.should_autocommit. This property has been removed in SQLAlchemy 2.0.
To fix, the if statement can simply be removed as it is no longer needed. See #291 for more details.
Resolves #291 
The current dialect is incompatible with SQLAlchemy version 2.0. This change makes the dialect compatible.
```markdown
* Add support for SQLAlchemy 2.0. ({issue}`291`)
```
> SQLAlchemy 2.0 Compatibility

- tests/integration/test_dbapi_integration.py
- trino/dbapi.py
resolves #279 
Now it is possible to chain fetch operations. Added test for it.
> Support execute chaining

- tests/integration/test_dbapi_integration.py
- trino/constants.py
- trino/dbapi.py
Add internal_size, precision, scale to Cursor.description to make it easier to get type information of a result set.
Note that if this information can be extracted from the type, this is also removed from the type_code, making it easier to match upon.
```markdown
* Add type information to DBAPI's cursor description (internal_size, scale, precision)
```
> Enhance `Cursor.description` with type information

- CHANGES.md
Assemble the release notes for the upcoming 0.321.0 release. Fixes https://github.com/trinodb/trino-python-client/issues/298
N/A
Format: committer/maintainer, PR/issue number, ✅ / ❌ ✅ - release note added and verified, or assessed to be not necessary, set to ❌ before completion
@hashhar #252, #27 ✅
@hashhar #299 ✅
@hashhar #302 ✅
@hashhar #300 ✅
@hashhar #311 ✅
@hashhar #307 ✅
@hashhar #305, #308 ✅
@hashhar #279, #316 ✅
@hashhar #315 ✅
> Release notes for 0.321.0

- README.md
Resolves #317 
Added table with mapping from Trino to python types.
Should I mention somehow unusual types which aren't mapped to python types? E.g. `INTERVAL YEAR TO MONTH`, `INTERVAL DAY TO SECOND`, `UUID` etc.
> Add Trino - Python types mapping

- tests/integration/test_dbapi_integration.py
- trino/client.py
- trino/dbapi.py
Resolves #319 
```markdown
* Provide row count on dbapi's Cursor for DML queries
```
> Provide rowcount for DML queries

- trino/client.py
Align query cancellation with JDBC driver
> Align query cancellation with JDBC driver

- tests/integration/test_dbapi_integration.py
- tests/unit/test_client.py
- trino/client.py
- trino/dbapi.py
Provide sql read-only property on dbapi cursor
```markdown
* Provide executed SQL statement as a read-only property on dbapi's cursor
```
> Provide query read-only property on dbapi cursor

- README.md
- tests/unit/test_dbapi.py
- trino/dbapi.py
(*) Release notes are required, with the following suggested text:
```markdown
* Assign port, http schema automatically based on passed hostname
```
> Assign port, http schema automatically based on passed hostname

- tests/integration/test_dbapi_integration.py
- trino/client.py
```
cur = trino_connection.cursor()
cur.execute("SELECT CAST(ROW(1, 2e0) AS ROW(x BIGINT, y DOUBLE))")
rows = cur.fetchall()
assert rows[0][0] == (1, 2.0)
assert rows[0][0].x == 1
assert rows[0][0].y == 2.0
cur = trino_connection.cursor()
cur.execute("SELECT CAST(ROW(1, ROW(1, 2e0)) AS ROW(x BIGINT, y ROW(x BIGINT, y DOUBLE)))")
rows = cur.fetchall()
assert rows[0][0] == (1, (1, 2.0))
assert rows[0][0].x == 1
assert rows[0][0].y.x == 1
assert rows[0][0].y.y == 2.0
```
```markdown
* Make names of ROW datatype available in result set
```
Fixes …
> Make names of ROW datatype available in result set

- README.md
- tests/integration/test_dbapi_integration.py
- trino/client.py
> Add role parameter

- tests/integration/test_sqlalchemy_integration.py
- trino/sqlalchemy/datatype.py
Provide a SQLAlchemy mapping to Trino's UUID type (resolves issue #331 )
Provide UUID support for SQLAlchemy
(X) Release notes are required, with the following suggested text:
```markdown
* Support UUID for SQLAlchemy ({issue}`358`)
```
> Support UUID for SQLAlchemy

- setup.py
- tests/integration/test_dbapi_integration.py
- tests/integration/test_types_integration.py
- trino/client.py
- trino/dbapi.py
This PR addresses https://github.com/trinodb/trino-python-client/issues/366. 
Per [this](https://blog.ganssle.io/articles/2018/03/pytz-fastest-footgun.html) article, there seemed to be merit in removing `pytz` in favor of `dateutil.tz` given that in Python 3.6 the `datetime` module remedied the ambiguous datetimes due to daylight saving time transition. 
Regrettably though one cannot obtain the IANA name from a `dateutil.tz` time zone—which is required when transpiling `datetime.time`/`datetime.datetime` objects to Trino SQL when provided as operation parameters. Instead we use the `zoneinfo` package (added to Python’s standard library in Python 3.9 and back ported) which does provide a mechanism of obtaining the specified IANA name from a `datetime.datetime`/`datetime.time` object, i.e., …
> Address time zone localization issue

- tests/integration/test_sqlalchemy_integration.py
- trino/sqlalchemy/dialect.py
> Add lazy evaluation of `server_version_info`

- tests/integration/test_dbapi_integration.py
- tests/integration/test_sqlalchemy_integration.py
- trino/dbapi.py
- trino/sqlalchemy/dialect.py
- trino/sqlalchemy/util.py
Make parametrized statement executions more efficient by taking advantage of https://github.com/trinodb/trino/pull/17341.
When running against older versions of Trino that don't support the `EXECUTE IMMEDIATE` statement, the old behavior can be restored by passing `legacy_prepared_statements=True` when creating a connection.
Draft PR until the back-end change is released.
(X) Release notes are required, please propose a release note for me.
```markdown
```
> Use `EXECUTE IMMEDIATE` for parameterized statement executions

- tests/unit/test_client.py
- trino/client.py
- trino/dbapi.py
In be74586c29f2583c3e62de2a07183ad67857511c the redirect_handler code was removed but only partially.
This change removes the rest of the dead code related to redirect_handler.
```markdown
```
> Remove unused 'redirect_handler' code

- trino/client.py
- trino/exceptions.py
Wrap all requests.exceptions.RequestException as TrinoConnectionError.
Fixes #364.
Before this change if a user needed to catch connection errors (e.g. connection refused) they needed to add a dependency on requests and import the relevant exception from requests.exceptions module.
After this change all requests exception get rethrown as a TrinoConnectionError instead.
(x) Release notes are required, please propose a release note for me.
```markdown
```
> Wrap all requests.exceptions.RequestException as TrinoConnectionError

- tests/integration/test_sqlalchemy_integration.py
- trino/sqlalchemy/dialect.py
I'd like to provide standard function `get_catalog_names` in SQLAlchemy's `TrinoDialect`.  
This function could be used to list and switch between catalogs by client like proposed in Superset [SIP-95](https://github.com/apache/superset/issues/22862)
```markdown
```
> implement `get_catalog_names`

- tests/unit/test_client.py
- trino/client.py
- trino/constants.py
Trino introduces some breaking changes for old client versions but there is no way to find out the client version of our users to warn them before upgrading to a newer version since the python client is using the default user agent from `requests` that results `python-requests/2.31.0`. However, the JDBC driver [sets](https://github.com/trinodb/trino/blob/423/client/trino-jdbc/src/main/java/io/trino/jdbc/NonRegisteringTrinoDriver.java#L123) a more descriptive user agent header value such as `Trino JDBC Driver/371` that helps us to identify users with outdated client versions.
This PR aims to specify the user agent to pass the current driver version to the coordinator to be logged later in query created and completed events as [`io.trino.spi.eventlistener.QueryContext.userAgent`](https://git …
> add Trino Python Client version to user agent

- tests/unit/sqlalchemy/test_dialect.py
- trino/sqlalchemy/dialect.py
Adds support for the 'externalAuthentication' Trino query URL parameter.
If 'externalAuthentication' is passed on the query arguments:
- Sets 'http_scheme' to 'https' 
- Sets 'auth' to OAuth2Authentication()
It allows to use SQLAlchemy with OAuth2Authentication.
( x ) Release notes are required, with the following suggested text:
```markdown
* Add support to 'externalAuthentication' SQLAlchemy URL parameter.  ({issue}`#343`)
```
closes #343
> feat(sqlalchemy): Add Support for externalAuthentication

- tests/integration/test_dbapi_integration.py
- trino/dbapi.py
fixes #414
```markdown
* Fix fetchall doesn't respect the cursor position ({issue}`414`)
```
> fix fetchall returns remaining cursor

- tests/unit/test_dbapi.py
- trino/dbapi.py
Fixes an issue where if `cursor.description` is called before `execute`, then it returns `AttributeError` for `columns`. This make this client not work with [Ray Data](https://github.com/ray-project/ray/blob/master/python/ray/data/datasource/sql_datasource.py#L71-L81) because it checks if `description` exists.
Guard against error state when calling a function
> Check cursor _query is None before columns

- tests/integration/test_dbapi_integration.py
- trino/dbapi.py
Fixes https://github.com/trinodb/trino-python-client/issues/428
```markdown
```
> Fix closing cursor with no previously running query

- tests/integration/test_sqlalchemy_integration.py
- trino/sqlalchemy/compiler.py
- trino/sqlalchemy/datatype.py
- trino/sqlalchemy/dialect.py
Resolves https://github.com/trinodb/trino-python-client/issues/423 and https://github.com/trinodb/trino-python-client/issues/387
```markdown
```
> Fix JSON support in SQLAlchemy

- trino/sqlalchemy/dialect.py
- This PR attempts to handle the error when fetching Hudi tables schema in Superset and close https://github.com/apache/superset/issues/21945
Presto does support the $partitions table suffix per [the release notes](https://prestodb.io/docs/current/release/release-0.199.html) but Trino seems not to support this so this should be removed (?)
```log
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/flask_appbuilder/api/__init__.py", line 110, in wraps
return f(self, *args, **kwargs)
File "/app/superset/views/base_api.py", line 127, in wraps
raise ex
File "/app/superset/views/base_api.py", line 121, in wraps
duration, response = time_function(f, self, *args, **kwargs)
File "/app/superset/utils/core.py", line 1454, in time_function
response = func(*args, **kwargs) …
```
> Suppress failure when reading $partitions system table in get_indexes

- trino/logging.py
Before this change we called `setLevel` on each logger with level set to INFO. This meant that it was not possible to change log level for all child modules by doing something like
`logging.getLogger('trino').setLevel(logging.DEBUG)` because the child loggers had explicit levels set already. It instead required us to change log levels for each module (`trino.client`, `trino.dbapi`, `trino.auth` etc.) separately.
After this change only the root logger `trino` has a default level set. Other child loggers inherit from it. So now the default log level for all modules can be changed by doing
`logging.getLogger('trino').setLevel(logging.DEBUG)` for example.
Make it easy to configure log level for all modules at once.
( …
> Only set log level for the root logger

- tests/unit/sqlalchemy/test_compiler.py
- trino/sqlalchemy/compiler.py
Adds a simple compiler method for using the `IGNORE NULLS` functionality of window functions in Trino. I implemented this privately in a package for work but figured I could generalize it and add it to the package as a whole :)
```markdown
```
> Add a generic function compiler to handle `IGNORE NULLS` in window functions

- tests/integration/test_types_integration.py
- trino/mapper.py
Fix mapping of MAP types with boolean or integer keys.
This is on top of https://github.com/trinodb/trino-python-client/pull/440 so only last 3 commits need to be reviewed.
```markdown
* Fix mapping of MAP types with boolean or integer keys.
```
> Fix mapping of MAP types with boolean or integer keys

- tests/unit/conftest.py
- tests/unit/test_client.py
- trino/client.py
Add support for 'None' on response data 
```markdown
```
> Add support for 'None' on response data

- setup.cfg
- trino/mapper.py
- trino/types.py
Add type hints for mapper and types modules and enables mypy there.
This uncovered some dead code / possibly broken code regarding handling of ambiguous date-time values. This will be fixed separately in a follow-up.
> Type hints for types and mapper modules

- tests/integration/test_sqlalchemy_integration.py
- trino/sqlalchemy/compiler.py
Adds support for MAP type to SQLA dialect.
Fixes https://github.com/trinodb/trino-python-client/issues/397
Supersedes https://github.com/trinodb/trino-python-client/pull/398
This preserves commit authorship from https://github.com/trinodb/trino-python-client/pull/398.
```markdown
* Add support for `MAP` to SQLAlchemy dialect.
```
> Add support for MAP type to SQLAlchemy dialect

- .github/workflows/ci.yml
- .github/workflows/release.yml
- .pre-commit-config.yaml
- setup.py
- tests/unit/sqlalchemy/conftest.py
- Update GitHub action versions
- Add pip caching for CI workflows, release workflow doesn't use caching still just for safety/clean build reasons
> CI updates

- .github/workflows/ci.yml
- README.md
- setup.py
- tests/unit/test_client.py
- trino/auth.py
Add yet another Authentication method, via `requests-gssapi`. The provided class, `GSSAPIAuthentication` is complete copy-paste of `KerberosAuthentication`, but uses a much nicer library (`requests-gssapi`) underneath.
Added support for alternative method of kerberos authentication.
```markdown
* Add requests-gssapi based authentication via `GSSAPIAuthentication`. ({issue}`454`)
```
> Add GSSAPIAuthentication authentication class.

- tests/integration/test_sqlalchemy_integration.py
- trino/sqlalchemy/compiler.py
Resolves https://github.com/trinodb/trino-python-client/issues/458
```markdown
```
> Add support for ROW and ARRAY in TrinoTypeCompiler

- tests/unit/test_client.py
- trino/client.py
I want `extra_credential` to accept an object as a value. This is helpful because it allows pass through of short lived tokens (JWT or otherwise) that can be refreshed by the client without having to generate a new engine/client object.
Presently this is not possible because `parse_quote` does a [check](https://github.com/python/cpython/blob/de1428f8c234a8731ced99cbfe5cd6c5c719e31d/Lib/urllib/parse.py#L916) on the object type.
Therefore it is necessary to call `str()` on the `extra_credential` value during serialisation.
Support object as value in `extra_credential` to support refreshing tokens.
(x) Release notes are required, with the …
> Support object as value in extra_credential

- tests/unit/test_client.py
- trino/client.py
- trino/constants.py
This PR is to support `SET SESSION AUTHORIZATION user` and `RESET SESSION AUTHORIZATION` sql commands on the python client. Those 2 sql commands are supported on the server side from this PR https://github.com/trinodb/trino/pull/16067
Related to issue https://github.com/trinodb/trino/issues/2512
Tested locally with the script:
```python
from trino.dbapi import connect
conn = connect(
host="localhost",
port=8080,
user="baozhang",
catalog="tpch"
)
cur = conn.cursor()
cur.execute("SELECT COUNT(*) FROM tpch.sf1.orders")
rows = cur.fetchall()
assert rows[0][0] == 1500000
cur.execute("SELECT CURRENT_USER")
rows = cur.fetchall()
assert rows[0][0] == 'baozhang'
cur.execute("SET SESSION AUTHORIZATION 'prestodv'")
cur.execute("SELECT CURRENT_USER")
rows = cur.fetchall()
assert rows[0][0] == …
```
> Support SET SESSION AUTHORIZATION on trino-python-client

- tests/unit/test_client.py
- trino/auth.py
Resolves https://github.com/trinodb/trino-python-client/issues/444
```markdown
```
> Apply new logic for parsing WWW-Authenticate header

- .pre-commit-config.yaml
- setup.cfg
- setup.py
- trino/auth.py
- trino/types.py
Remove normalize method from TemporalType.
Related to https://github.com/trinodb/trino-python-client/issues/449
```markdown
```
> Remove normalize method from TemporalType

- setup.py
- tests/unit/test_client.py
- tests/unit/test_dbapi.py
- trino/auth.py
- trino/constants.py
Currently, storing a long JWT token on Windows triggers the following error:
```
During handling of the above exception, another exception occurred:
....
File "\lib\site-packages\trino\auth.py", line 403, in _authenticate
self._attempt_oauth(response, **kwargs)
File "\lib\site-packages\trino\auth.py", line 449, in _attempt_oauth
self._store_token_to_cache(key, token)
File "\lib\site-packages\trino\auth.py", line 498, in _store_token_to_cache
self._token_cache.store_token_to_cache(key, token)
File "\lib\site-packages\trino\auth.py", line 360, in store_token_to_cache
_password
get_keyring().set_password(service_name, username, password)
File "\lib\site-packages\keyring\backends\Windows.py", line 128, in set_password
self._set_password(service, username, str(password))
File …
```
> Shard long JWT token on Windows

- tests/unit/sqlalchemy/test_compiler.py
- trino/sqlalchemy/compiler.py
I have added a `visit_try_cast()` method to `trino.sqlalchemy.compiler.TrinoSQLCompiler`. This fixes [issue 473](https://github.com/trinodb/trino-python-client/issues/473).
This allows Trino's [`try_cast()`](https://trino.io/docs/current/functions/conversion.html#try_cast) to be used in SQLAlchemy.
> Add visit_try_cast to sqlalchemy compiler

- tests/unit/sqlalchemy/test_dialect.py
- trino/sqlalchemy/dialect.py
Previous version of code contained an always true condition that may lead to unintended behaviour. This bug was captured by flake8 linter, so it may be a good idea to include it as a part of CI process.
```markdown
* Fix `cert` and `key` kwargs parsing from URL in sqlachemy's `create_connect_args` function
```
> Fix `cert` and `key` kwargs parsing from URL in sqlachemy's `create_connect_args` function

- tests/unit/oauth_test_utils.py
- trino/auth.py
This PR applies a minimal change to fix the issue where the OAuth refresh token flow results in the "Header info didn't have x_token_server" error:
```
trino.exceptions.TrinoAuthError: Error: header info didn't have x_token_server
```
This error was introduced in #467. The regression was not captured by the test `test_oauth2_refresh_token_flow`; Trino returns multi-valued `Www-Authenticate` headers while `PostStatementCallback` does not, and the new parsing logic does not handle this appropriately. This PR also updates the test.
This PR fixes the issue where Trino returns "Header info didn't have x_token_server" after some time and starts working again after a longer time. 
( ) Release notes are required, please …
> Fix www-authenticate header parsing bug when refreshing tokens

- trino/sqlalchemy/dialect.py
Resolves https://github.com/trinodb/trino-python-client/issues/476
`get_indexes` refactored to return list of dicts with partition name and partition values.
example output:
```python
[
{
'partition_name': 'part_a',
'partition_values': ['val1', 'val2', 'val3']
},
{
'partition_name': 'part_b',
'partition_values': ['val4', 'val5', 'val6']
}
]
```
```markdown
```
> Refactor get_indexes to return partition names and values

- .github/workflows/ci.yml
- README.md
- setup.py
- tests/integration/test_dbapi_integration.py
- tests/integration/test_types_integration.py
- tests/unit/test_client.py
- tox.ini
- trino/client.py
- trino/dbapi.py
- trino/mapper.py
Drop support for end-of-life Python 3.8
Remove backports.zoneinfo dependency
```markdown
* Drop support for end-of-life Python 3.8 and add support for Python 3.13. ({issue}`issuenumber`)
```
> Drop support for end-of-life Python 3.8

- tests/integration/test_types_integration.py
- trino/mapper.py
Resolves https://github.com/trinodb/trino-python-client/issues/356
- Map INTERVAL YEAR TO MONTH to `relativedelta`
- Map INTERVAL DAY TO SECOND to `timedelta`
```markdown
```
> Map INTERVAL types to Python types

- tests/unit/test_client.py
- trino/auth.py
Currently the function to parse the authorization header doesn't support urls containing parameters. This PR addresses this.
```markdown
* Fix authentication parsing to allow urls containing url parameters
```
> Fix parsing authentication header

- tests/unit/test_types.py
- trino/types.py
Ensure `NamedRowTuple` `pickle` roundtrips  successfully. 
Added tests for all custom types.
Fixes #490.
Implement necessary `pickle` methods to ensure type can be pickled/unpickled correctly.
Support pickle serialization/deserialization for rows.
(x) Release notes are required, with the following suggested text: 
```markdown
* Ensure custom types support pickling. ({issue}`490`)
```
> Ensure custom types support pickling.

- trino/client.py
Type annotations for the `client.ClientSession` class based on constructor arguments and in-constructor behavior.
Release notes are required, with the following suggested text:
```markdown
* Add type annotations to `client.ClientSession`.
```
> Add missing type annotations for the "ClientSession" class

- tests/unit/test_client_session.py
Tests for the `client.ClientSession` class, including getters and setters. Relatively simple except the `roles` property.
This is not user-visible or docs only and no release notes are required.
> Add tests for the "ClientSession" class

- trino/auth.py
- trino/client.py
Type annotations for the `client.TrinoRequest` class based on usages and tests.
Release notes are required, with the following suggested text:
```markdown
* Add type annotations for `client.TrinoRequest`.
```
> Add missing type annotations for the "TrinoRequest" class

- README.md
- etc/catalog/jmx.properties
- etc/catalog/memory.properties
- etc/catalog/tpcds.properties
- etc/catalog/tpch.properties
- etc/config-pre-466.properties
- etc/config.properties
- etc/jvm-pre-466.config
- etc/jvm.config
- etc/spooling-manager.properties
- setup.py
- tests/development_server.py
- tests/integration/conftest.py
- tests/integration/test_dbapi_integration.py
- tests/integration/test_sqlalchemy_integration.py
- tests/integration/test_types_integration.py
- tests/unit/test_client.py
- trino/client.py
- trino/constants.py
- trino/dbapi.py
Support Spooling Protocol
(*) Release notes are required, with the following suggested text:
```markdown
* Support Spooling Protocol
```
> Support Spooling Protocol

- trino/client.py
When the `error` field in the REST response is `null` (`None` for the python client), assume a successful execution.
From the [docs](https://trino.io/docs/current/develop/client-protocol.html):
> If query failed, the error attribute contains a QueryError object. That object contains a message, an errorCode and other information about the error. See the io.trino.client.QueryError class in module trino-client in the client directory for more details.
> queryError | QueryError | Non-null only if the query resulted in an error.
However, sometimes (some versions of Trino) the server returns an HTTP response with the `error` field present, yet with a `None` value. Then, an exception is thrown in the client:
```bash
Traceback (most recent call last):
File "/OBFUSCATED/main.py", line 29, in …
```
> fix: account for None in error field of http response

- tests/integration/test_dbapi_integration.py
- trino/client.py
This makes the API much easier to consume in the `segments` cursor style:
```
cur = conn.cursor('segment')
cur.execute(sql)
segments = cur.fetchall()
total_row_count = 0
row_mapper = RowMapperFactory().create(columns=cur._query.columns, legacy_primitive_types=False)
for segment in segments:
rows = list(SegmentIterator(segment, row_mapper))
print ("rows length is " + str(len(rows)) + " " + segment.encoding)
total_row_count += len(rows)
print(total_row_count)
```
This will work the same:
```
segments = cur.fetchall()
total_row_count = 0
row_mapper = RowMapperFactory().create(columns=cur._query.columns, legacy_primitive_types=False)
rows = list(SegmentIterator(segments, row_mapper))
print ("rows length is " + str(len(rows)))
total_row_count += len(rows)
print(total_row_count)
```
> Introduce DecodableSegment and remove Tuple in iterators

- README.md
Documentation regarding usage of the `http_session` parameter is lacking. Simple example may be helpful.
```markdown
```
> Document usage of the http_session parameter

- tests/unit/sqlalchemy/test_dialect.py
- trino/client.py
- trino/sqlalchemy/dialect.py
The Trino Python client currently rejects all authentication attempts over HTTP. While this seems like is a sensible security measure on the part of the Trino client, using an HTTP URL to access the Trino server does not inherently indicate an insecure environment.
This could be useful for testing purposes or in modern service meshes, such as those using SPIFFE authentication where injection of the spiffe headers and adding TLS are handled by spire and envoy separately in sidecars ([doc here](https://spiffe.io/docs/latest/microservices/envoy/)). Furthermore the trino server also has the option of `http-server.authentication.allow-insecure-over-http=true` ([doc here](https://trino.io/docs/current/security/tls.html#configure-the-coordinator)) so it might be reasonable to not rejecting …
> Allow authentication over HTTP

- trino/auth.py
Fix #513 by correcting `mutual_authentication` type annotation and adding corresponding mutual authentication modes constants.
* Introduce constants for Kerberos and GSSAPI mutual authentication modes within `KerberosAuthentication` and `GSSAPIAuthentication` classes.
* Set proper type annotations and default values for `mutual_authentication` attributes.
* Default values are replicated from corresponding defaults in `requests_kerberos`/`requests_gssapi`.
Kerberos/GSSAPI libraries (`requests_kerberos` and `requests_gssapi`) expect `mutual_authentication` parameter to be an integer:
* `1` for "required"
* `2` for "optional"
* `3` for "disabled"
However, the same parameter in `trino-python-client` is annotated as `bool`. By luck, due to the order of conditions and the fact that `True == 1`, …
> Fix typing of kerberos mutual_authentication

- tests/unit/test_client.py
- trino/client.py
PR seeks to resolve issue https://github.com/trinodb/trino-python-client/issues/545.
[Trino expects the Client Capabilities header](https://github.com/trinodb/trino/blob/71390927f48d0aaf1372476e761fdf4a427ccb96/core/trino-main/src/main/java/io/trino/execution/SetSessionAuthorizationTask.java#L67-L69) `SESSION_AUTHORIZATION` exists so that it allows the `SET SESSION AUTHORIZATION`.
[This wasn't added in the initial PR](https://github.com/trinodb/trino-python-client/pull/349)
(x) Release notes are required, please propose a release note for me.
```markdown
* Fix `SET SESSION AUTHORIZATION` not working. ({issue}`545`)
```
> add SESSION_AUTHORIZATION to client capabilities

- tests/unit/conftest.py
- tests/unit/test_dbapi.py
- trino/dbapi.py
Uses either `DEFAULT_TLS_PORT` (`443`) or `DEFAULT_PORT` (`8080`) if no explicit port is provided, based on the HTTP scheme of the connection URI.
```markdown
* Use default TLS port if scheme is HTTPS. ({issue}`#539`)
```
> Use default TLS port if scheme is HTTPS

- trino/auth.py
PR for https://github.com/trinodb/trino-python-client/issues/544
Make it possible to passing oauth link through Power User for DBT plugin.
```markdown
* Fix print oauth url without flush. ({issue}`544`)
```
> Fix print oauth url without flush

- trino/client.py
When setting SSL Verify flag to false, use that in HTTP requests, for example, HTTP requests for spooled segments
HTTP SSL Verification flag not passed to SpooledSegment class which fails HTTP requests
SSL Verification flag set to False when initialising a connection to Trino is not passed to HTTP requests for spooled segments and therefore fails with HTTP SSL errors
```markdown
* Fix issue: [543](https://github.com/trinodb/trino-python-client/issues/543)
```
> Pass HTTP SSL verify flag

- tests/unit/test_dbapi.py
- trino/dbapi.py
Resolves #556 #557 
Include inferring http_scheme from port, in logic which sets http_scheme.
```markdown
```
> Fix logic for setting http_scheme

- trino/client.py
`get_localzone_name` was added in `tzlocal 4.0` and not available in older version.
Move the import to provide a workaround using older version of tzlocal
```markdown
```
> import get_localzone_name only if timezone not avaiable

- setup.py
- tests/unit/test_client.py
- trino/client.py
It is way faster than the current json parser: https://github.com/ijl/orjson?tab=readme-ov-file#performance
```markdown
```
> Migrate from built-in json to faster orjson

- tests/unit/sqlalchemy/test_compiler.py
- trino/sqlalchemy/compiler.py
Define custom visitors in `TrinoDDLCompiler` to ignore constraints.
By default, SQLAlchemy adds `PRIMARY KEY` and other constraint keywords to table creation DDL when these constraints are defined on a `Table` or class derived from declarative base. Since Trino does not support constraints, this results in invalid SQL. With this change the trino sqlalchemy extension now ignores primary key, foreign key and unique constraints when generating table DDL.
```markdown
* ignore constraints for table DDL generation
```
> Ignore primary key, foreign key and unique constraints for DDL generation
